version: '2.1'
services:
    # https://hub.docker.com/r/hazelcast/hazelcast/
    hazelcast:
        image: hazelcast/hazelcast:latest
        environment:
            - HZ_CLUSTERNAME=dev
            - HZ_NETWORK_PORT_AUTOINCREMENT=true
            - HZ_NETWORK_PORT_PORTCOUNT=100
            - HZ_NETWORK_PORT_PORT=5701
            - PROMETHEUS_PORT=8080
        ports:
            - "8080:8080"
    hazelcast2:
        image: hazelcast/hazelcast:latest
        environment:
            - HZ_CLUSTERNAME=dev
            - HZ_NETWORK_PORT_AUTOINCREMENT=true
            - HZ_NETWORK_PORT_PORTCOUNT=100
            - HZ_NETWORK_PORT_PORT=5701    
            - PROMETHEUS_PORT=8080        
        ports:
            - "8081:8080"
    # https://github.com/jboss-fuse/jboss-fuse-docker
    fuse:
        build: fuse
        ports:
             # web UI
            - "8181:8181"