#
# The MIT License
# Copyright © 2021 Subhrodip Mohanta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

name: Master CI

on:
  push:
    branches: master

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,darwin/amd64
            push: true
            tags: |
              subhrodip/jboss-fuse:790053
              subhrodip/jboss-fuse:fuse-790053
              subhrodip/jboss-fuse:7.9.0.fuse-790053
              subhrodip/jboss-fuse:7.9.0
              subhrodip/jboss-fuse:latest
              ghcr.io/ohbus/jboss-fuse:790053
              ghcr.io/ohbus/jboss-fuse:fuse-790053
              ghcr.io/ohbus/jboss-fuse:7.9.0.fuse-790053
              ghcr.io/ohbus/jboss-fuse:7.9.0
              ghcr.io/ohbus/jboss-fuse:latest
