#
# The MIT License
# Copyright © 2021 Subhrodip Mohanta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

name: PR Checker

on:
  pull_request:
    branches: [ '**' ]
    types: [opened, synchronize, reopened]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build-and-push:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push FUSE Help Application Docker Image to GHCR.io
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: Dockerfile
          registry: ghcr.io
          repository: ohbus/jboss-fuse-docker
          tags: pr-${{ env.PR_NUMBER }}
          labels: pipeline_build=github,cloud_build=azure,org.opencontainers.image.source=https://github.com/ohbus/jboss-fuse-docker
          push: false
